[webservers]
server1 ansible_host=192.168.1.106 ansible_user=student http_port=80
server2 ansible_host=192.168.1.107 ansible_user=student http_port=80

[balancer]
balancer ansible_host=192.168.1.102 ansible_user=student caddy_port=80

[postgres]
postgres ansible_host=192.168.1.103 ansible_user=student postgres_port=5432 postgres_user=admin postgres_db=hexletdb

[all:vars]
ansible_python_interpreter=/usr/bin/python3